version: "3"

networks:
  mysql-network:
    driver: bridge

services:
  mysql-server-1:
    networks:
      - mysql-network
    container_name: mysql-server-1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_SERVER_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_SERVER_ROOT_HOST}
    image: mysql/mysql-server:8.0.12
    ports:
      - "3301:3306"
    command:
      [
        "mysqld",
        "--server_id=1",
        "--binlog_checksum=NONE",
        "--gtid_mode=ON",
        "--enforce_gtid_consistency=ON",
        "--log_bin",
        "--log_slave_updates=ON",
        "--master_info_repository=TABLE",
        "--relay_log_info_repository=TABLE",
        "--transaction_write_set_extraction=XXHASH64",
        "--user=mysql",
        "--skip-host-cache",
        "--skip-name-resolve",
        "--default_authentication_plugin=mysql_native_password",
      ]
  mysql-server-2:
    networks:
      - mysql-network
    container_name: mysql-server-2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_SERVER_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_SERVER_ROOT_HOST}
    image: mysql/mysql-server:8.0.12
    ports:
      - "3302:3306"
    command:
      [
        "mysqld",
        "--server_id=2",
        "--binlog_checksum=NONE",
        "--gtid_mode=ON",
        "--enforce_gtid_consistency=ON",
        "--log_bin",
        "--log_slave_updates=ON",
        "--master_info_repository=TABLE",
        "--relay_log_info_repository=TABLE",
        "--transaction_write_set_extraction=XXHASH64",
        "--user=mysql",
        "--skip-host-cache",
        "--skip-name-resolve",
        "--default_authentication_plugin=mysql_native_password",
      ]
  mysql-server-3:
    networks:
      - mysql-network
    container_name: mysql-server-3
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_SERVER_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_SERVER_ROOT_HOST}
    image: mysql/mysql-server:8.0.12
    ports:
      - "3303:3306"
    command:
      [
        "mysqld",
        "--server_id=3",
        "--binlog_checksum=NONE",
        "--gtid_mode=ON",
        "--enforce_gtid_consistency=ON",
        "--log_bin",
        "--log_slave_updates=ON",
        "--master_info_repository=TABLE",
        "--relay_log_info_repository=TABLE",
        "--transaction_write_set_extraction=XXHASH64",
        "--user=mysql",
        "--skip-host-cache",
        "--skip-name-resolve",
        "--default_authentication_plugin=mysql_native_password",
      ]
  mysql-shell:
    networks:
      - mysql-network
    container_name: mysql-shell
    environment:
      MYSQL_USER: ${MYSQL_SHELL_USER}
      MYSQL_HOST: ${MYSQL_SHELL_HOST}
      MYSQL_PORT: ${MYSQL_SHELL_PORT}
      MYSQL_PASSWORD: ${MYSQL_SHELL_PASSWORD}
      MYSQLSH_SCRIPT: ${MYSQLSH_SHELL_SCRIPT}
      MYSQL_SCRIPT: ${MYSQL_SHELL_SCRIPT}
    image: neumayer/mysql-shell-batch
    volumes:
      - ./scripts/:/scripts/
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
  mysql-router:
    networks:
      - mysql-network
    container_name: mysql-router
    environment:
      MYSQL_USER: ${MYSQL_ROUTER_USER}
      MYSQL_HOST: ${MYSQL_ROUTER_HOST}
      MYSQL_PORT: ${MYSQL_ROUTER_PORT}
      MYSQL_PASSWORD: ${MYSQL_ROUTER_PASSWORD}
      MYSQL_INNODB_NUM_MEMBERS: ${MYSQL_ROUTER_INNODB_NUM_MEMBERS}
      MYSQL_CREATE_ROUTER_USER: ${MYSQL_ROUTER_CREATE_ROUTER_USER}
    image: mysql/mysql-router:8.0
    ports:
      - "6446:6446"
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
      - mysql-shell
    restart: on-failure
